import type { Strategy } from "@shared/schema";

export type StrategyCategory = 
  | "basic" 
  | "bullish" 
  | "bearish" 
  | "neutral" 
  | "volatility_long" 
  | "volatility_short" 
  | "butterflies" 
  | "advanced";

export type StrategySentiment = "very_bearish" | "bearish" | "neutral" | "directional" | "bullish" | "very_bullish";
export type RiskLevel = "limited" | "unlimited" | "capped";

export interface StrategyMetadata {
  category: StrategyCategory;
  sentiment: StrategySentiment[];
  tags: string[];
  riskLevel: RiskLevel;
  profitPotential: RiskLevel;
  maxProfit: string;
  maxLoss: string;
  breakeven: string;
}

export interface ExtendedStrategy extends Omit<Strategy, "id" | "underlyingPrice"> {
  metadata: StrategyMetadata;
}

export const categoryLabels: Record<StrategyCategory, string> = {
  basic: "Basic / Novice",
  bullish: "Directional - Bullish",
  bearish: "Directional - Bearish",
  neutral: "Neutral / Range Bound",
  volatility_long: "Volatility - Long",
  volatility_short: "Volatility - Short",
  butterflies: "Butterflies",
  advanced: "Advanced / Exotic",
};

export const sentimentLabels: Record<StrategySentiment, string> = {
  very_bearish: "Very Bearish",
  bearish: "Bearish",
  neutral: "Neutral",
  directional: "Directional",
  bullish: "Bullish",
  very_bullish: "Very Bullish",
};

export const strategyTemplates: ExtendedStrategy[] = [
  // ==================== BASIC / NOVICE ====================
  {
    name: "Long Call",
    description: "A basic bullish strategy for beginners with potential for significant returns. Buy a call option granting the right to purchase stock at the strike price. Profit from upside moves while limiting loss to premium paid.",
    legs: [
      {
        id: "1",
        type: "call",
        position: "long",
        strike: 105,
        quantity: 1,
        premium: 3.5,
        expirationDays: 30,
      },
    ],
    metadata: {
      category: "basic",
      sentiment: ["bullish", "very_bullish"],
      tags: ["Bullish", "Limited Loss", "Unlimited Profit", "Vol Long"],
      riskLevel: "limited",
      profitPotential: "unlimited",
      maxProfit: "Unlimited",
      maxLoss: "Premium Paid",
      breakeven: "Strike + Premium",
    },
  },
  {
    name: "Long Put",
    description: "A bearish strategy where you buy a put option expecting the underlying to decrease. You have the right to sell at the strike price. Maximum loss is limited to premium paid.",
    legs: [
      {
        id: "1",
        type: "put",
        position: "long",
        strike: 95,
        quantity: 1,
        premium: 3.0,
        expirationDays: 30,
      },
    ],
    metadata: {
      category: "basic",
      sentiment: ["bearish", "very_bearish"],
      tags: ["Bearish", "Limited Loss", "High Profit", "Vol Long"],
      riskLevel: "limited",
      profitPotential: "capped",
      maxProfit: "Strike - Premium (if stock goes to $0)",
      maxLoss: "Premium Paid",
      breakeven: "Strike - Premium",
    },
  },
  {
    name: "Covered Call",
    description: "Own 100 shares and sell a call option against them. Collect premium while holding stock. Max profit is capped at strike price. Ideal for generating income on stocks you already own.",
    legs: [
      {
        id: "stock",
        type: "stock",
        position: "long",
        strike: 100,
        quantity: 100,
        premium: 100,
        expirationDays: 30,
      },
      {
        id: "1",
        type: "call",
        position: "short",
        strike: 110,
        quantity: 1,
        premium: 2.5,
        expirationDays: 30,
      },
    ],
    metadata: {
      category: "basic",
      sentiment: ["neutral", "bullish"],
      tags: ["Income", "Vol Short", "Includes Stock"],
      riskLevel: "capped",
      profitPotential: "limited",
      maxProfit: "(Strike - Entry Price) × 100 + Premium",
      maxLoss: "Entry Price × 100 - Premium (if stock to $0)",
      breakeven: "Entry Price - Premium",
    },
  },
  {
    name: "Cash-Secured Put",
    description: "Sell a put while holding cash to buy shares if assigned. Collect premium income with a neutral-to-bullish outlook. If assigned, acquire shares at a discount.",
    legs: [
      {
        id: "1",
        type: "put",
        position: "short",
        strike: 95,
        quantity: 1,
        premium: 3.0,
        expirationDays: 30,
      },
    ],
    metadata: {
      category: "basic",
      sentiment: ["bullish", "neutral"],
      tags: ["Income", "Vol Short", "Cash Required"],
      riskLevel: "capped",
      profitPotential: "limited",
      maxProfit: "Premium Received",
      maxLoss: "Strike - Premium",
      breakeven: "Strike - Premium",
    },
  },
  {
    name: "Protective Put",
    description: "Own 100 shares and buy a put option as insurance. Protects against downside while maintaining unlimited upside. Like insurance for your stock position.",
    legs: [
      {
        id: "stock",
        type: "stock",
        position: "long",
        strike: 100,
        quantity: 100,
        premium: 100,
        expirationDays: 30,
      },
      {
        id: "1",
        type: "put",
        position: "long",
        strike: 95,
        quantity: 1,
        premium: 3.0,
        expirationDays: 30,
      },
    ],
    metadata: {
      category: "basic",
      sentiment: ["bullish"],
      tags: ["Protection", "Vol Long", "Includes Stock"],
      riskLevel: "limited",
      profitPotential: "unlimited",
      maxProfit: "Unlimited (stock can rise indefinitely)",
      maxLoss: "(Entry Price - Strike) × 100 + Premium",
      breakeven: "Entry Price + Premium",
    },
  },
  {
    name: "Collar",
    description: "Own 100 shares, sell a call, and buy a put. Limits both upside and downside. Low cost protection strategy that caps gains but protects against large losses.",
    legs: [
      {
        id: "stock",
        type: "stock",
        position: "long",
        strike: 100,
        quantity: 100,
        premium: 100,
        expirationDays: 30,
      },
      {
        id: "1",
        type: "call",
        position: "short",
        strike: 110,
        quantity: 1,
        premium: 2.0,
        expirationDays: 30,
      },
      {
        id: "2",
        type: "put",
        position: "long",
        strike: 90,
        quantity: 1,
        premium: 2.0,
        expirationDays: 30,
      },
    ],
    metadata: {
      category: "basic",
      sentiment: ["neutral", "bullish"],
      tags: ["Protection", "Vol Neutral", "Includes Stock"],
      riskLevel: "limited",
      profitPotential: "limited",
      maxProfit: "(Call Strike - Entry Price) × 100 + Net Credit",
      maxLoss: "(Entry Price - Put Strike) × 100 + Net Debit",
      breakeven: "Entry Price ± Net Premium",
    },
  },

  // ==================== DIRECTIONAL - BULLISH ====================
  {
    name: "Bull Call Spread",
    description: "Buy a call at a lower strike and sell a call at a higher strike. Reduces cost compared to a simple long call. Both profit and loss are capped. A moderately bullish debit spread.",
    legs: [
      {
        id: "1",
        type: "call",
        position: "long",
        strike: 100,
        quantity: 1,
        premium: 5.0,
        expirationDays: 30,
      },
      {
        id: "2",
        type: "call",
        position: "short",
        strike: 110,
        quantity: 1,
        premium: 2.0,
        expirationDays: 30,
      },
    ],
    metadata: {
      category: "bullish",
      sentiment: ["bullish"],
      tags: ["Bullish", "Limited Risk", "Vol Neutral"],
      riskLevel: "limited",
      profitPotential: "limited",
      maxProfit: "Width of Strikes - Net Debit",
      maxLoss: "Net Debit Paid",
      breakeven: "Long Strike + Net Debit",
    },
  },
  {
    name: "Bull Put Spread",
    description: "Sell a put at a higher strike and buy a put at a lower strike. Collect a net credit upfront. Profit when stock stays above the short strike. A bullish credit spread with limited risk.",
    legs: [
      {
        id: "1",
        type: "put",
        position: "short",
        strike: 100,
        quantity: 1,
        premium: 4.0,
        expirationDays: 30,
      },
      {
        id: "2",
        type: "put",
        position: "long",
        strike: 90,
        quantity: 1,
        premium: 1.5,
        expirationDays: 30,
      },
    ],
    metadata: {
      category: "bullish",
      sentiment: ["bullish", "neutral"],
      tags: ["Bullish", "Credit", "Vol Short"],
      riskLevel: "limited",
      profitPotential: "limited",
      maxProfit: "Net Credit Received",
      maxLoss: "Width of Strikes - Net Credit",
      breakeven: "Short Strike - Net Credit",
    },
  },
  {
    name: "Bull Call Ladder",
    description: "Buy 1 lower strike call, sell 1 middle strike call, sell 1 higher strike call. A bullish strategy with capped upside but reduced cost. Profits if stock rises moderately.",
    legs: [
      {
        id: "1",
        type: "call",
        position: "long",
        strike: 100,
        quantity: 1,
        premium: 5.0,
        expirationDays: 30,
      },
      {
        id: "2",
        type: "call",
        position: "short",
        strike: 105,
        quantity: 1,
        premium: 3.0,
        expirationDays: 30,
      },
      {
        id: "3",
        type: "call",
        position: "short",
        strike: 110,
        quantity: 1,
        premium: 1.5,
        expirationDays: 30,
      },
    ],
    metadata: {
      category: "bullish",
      sentiment: ["bullish"],
      tags: ["Bullish", "Vol Short", "Complex"],
      riskLevel: "unlimited",
      profitPotential: "limited",
      maxProfit: "K2 - K1 - Net Debit",
      maxLoss: "Unlimited above K3",
      breakeven: "K1 + Net Debit / K3 + Max Profit",
    },
  },
  {
    name: "Long Synthetic Future",
    description: "Buy a call and sell a put at the same strike. Replicates owning 100 shares of stock. Bullish strategy with unlimited profit and loss potential.",
    legs: [
      {
        id: "1",
        type: "call",
        position: "long",
        strike: 100,
        quantity: 1,
        premium: 4.0,
        expirationDays: 30,
      },
      {
        id: "2",
        type: "put",
        position: "short",
        strike: 100,
        quantity: 1,
        premium: 4.0,
        expirationDays: 30,
      },
    ],
    metadata: {
      category: "bullish",
      sentiment: ["bullish", "very_bullish"],
      tags: ["Bullish", "Synthetic", "Vol Neutral"],
      riskLevel: "unlimited",
      profitPotential: "unlimited",
      maxProfit: "Unlimited",
      maxLoss: "Strike - Net Debit (if stock to $0)",
      breakeven: "Strike + Net Cost",
    },
  },

  // ==================== DIRECTIONAL - BEARISH ====================
  {
    name: "Bear Put Spread",
    description: "Buy a put at a higher strike and sell a put at a lower strike. A moderately bearish debit spread with limited risk and limited reward.",
    legs: [
      {
        id: "1",
        type: "put",
        position: "long",
        strike: 100,
        quantity: 1,
        premium: 5.0,
        expirationDays: 30,
      },
      {
        id: "2",
        type: "put",
        position: "short",
        strike: 90,
        quantity: 1,
        premium: 2.0,
        expirationDays: 30,
      },
    ],
    metadata: {
      category: "bearish",
      sentiment: ["bearish"],
      tags: ["Bearish", "Limited Risk", "Vol Neutral"],
      riskLevel: "limited",
      profitPotential: "limited",
      maxProfit: "Width of Strikes - Net Debit",
      maxLoss: "Net Debit Paid",
      breakeven: "Long Strike - Net Debit",
    },
  },
  {
    name: "Bear Call Spread",
    description: "Sell a call at a lower strike and buy a call at a higher strike. Collect a net credit. Profit when stock stays below the short strike. A bearish credit spread.",
    legs: [
      {
        id: "1",
        type: "call",
        position: "short",
        strike: 100,
        quantity: 1,
        premium: 4.0,
        expirationDays: 30,
      },
      {
        id: "2",
        type: "call",
        position: "long",
        strike: 110,
        quantity: 1,
        premium: 1.5,
        expirationDays: 30,
      },
    ],
    metadata: {
      category: "bearish",
      sentiment: ["bearish", "neutral"],
      tags: ["Bearish", "Credit", "Vol Short"],
      riskLevel: "limited",
      profitPotential: "limited",
      maxProfit: "Net Credit Received",
      maxLoss: "Width of Strikes - Net Credit",
      breakeven: "Short Strike + Net Credit",
    },
  },
  {
    name: "Bear Put Ladder",
    description: "Sell 1 lower strike put, sell 1 middle strike put, buy 1 higher strike put. A bearish strategy that profits if stock falls moderately. Unlimited risk if stock crashes.",
    legs: [
      {
        id: "1",
        type: "put",
        position: "short",
        strike: 90,
        quantity: 1,
        premium: 1.5,
        expirationDays: 30,
      },
      {
        id: "2",
        type: "put",
        position: "short",
        strike: 95,
        quantity: 1,
        premium: 2.5,
        expirationDays: 30,
      },
      {
        id: "3",
        type: "put",
        position: "long",
        strike: 100,
        quantity: 1,
        premium: 5.0,
        expirationDays: 30,
      },
    ],
    metadata: {
      category: "bearish",
      sentiment: ["bearish"],
      tags: ["Bearish", "Vol Short", "Complex"],
      riskLevel: "unlimited",
      profitPotential: "limited",
      maxProfit: "K3 - K2 + Net Credit",
      maxLoss: "Unlimited below K1",
      breakeven: "K3 - Net Credit / K1 - Max Profit",
    },
  },
  {
    name: "Short Synthetic Future",
    description: "Buy a put and sell a call at the same strike. Replicates shorting 100 shares of stock. Bearish strategy with unlimited profit potential if stock falls.",
    legs: [
      {
        id: "1",
        type: "put",
        position: "long",
        strike: 100,
        quantity: 1,
        premium: 4.0,
        expirationDays: 30,
      },
      {
        id: "2",
        type: "call",
        position: "short",
        strike: 100,
        quantity: 1,
        premium: 4.0,
        expirationDays: 30,
      },
    ],
    metadata: {
      category: "bearish",
      sentiment: ["bearish", "very_bearish"],
      tags: ["Bearish", "Synthetic", "Vol Neutral"],
      riskLevel: "unlimited",
      profitPotential: "capped",
      maxProfit: "Strike - Net Debit (if stock to $0)",
      maxLoss: "Unlimited",
      breakeven: "Strike - Net Cost",
    },
  },
  {
    name: "Short Call",
    description: "Sell a call option to collect premium. Obligated to sell shares at strike if assigned. Best when expecting flat or declining prices. Unlimited risk if stock rises.",
    legs: [
      {
        id: "1",
        type: "call",
        position: "short",
        strike: 110,
        quantity: 1,
        premium: 2.5,
        expirationDays: 30,
      },
    ],
    metadata: {
      category: "bearish",
      sentiment: ["bearish", "neutral"],
      tags: ["Bearish", "Income", "Unlimited Risk"],
      riskLevel: "unlimited",
      profitPotential: "limited",
      maxProfit: "Premium Received",
      maxLoss: "Unlimited",
      breakeven: "Strike + Premium",
    },
  },
  {
    name: "Short Put",
    description: "Sell a put option to collect premium. Obligated to buy shares at strike if assigned. Bullish to neutral strategy that profits from time decay.",
    legs: [
      {
        id: "1",
        type: "put",
        position: "short",
        strike: 95,
        quantity: 1,
        premium: 2.5,
        expirationDays: 30,
      },
    ],
    metadata: {
      category: "bullish",
      sentiment: ["bullish", "neutral"],
      tags: ["Bullish", "Income", "Limited Profit"],
      riskLevel: "capped",
      profitPotential: "limited",
      maxProfit: "Premium Received",
      maxLoss: "Strike - Premium",
      breakeven: "Strike - Premium",
    },
  },

  // ==================== NEUTRAL / RANGE BOUND ====================
  {
    name: "Iron Condor",
    description: "Sell an OTM put spread and call spread. Collect premium from both sides. Profit when stock stays in a range. All risk and reward are defined.",
    legs: [
      {
        id: "1",
        type: "put",
        position: "long",
        strike: 90,
        quantity: 1,
        premium: 1.0,
        expirationDays: 30,
      },
      {
        id: "2",
        type: "put",
        position: "short",
        strike: 95,
        quantity: 1,
        premium: 2.0,
        expirationDays: 30,
      },
      {
        id: "3",
        type: "call",
        position: "short",
        strike: 105,
        quantity: 1,
        premium: 2.0,
        expirationDays: 30,
      },
      {
        id: "4",
        type: "call",
        position: "long",
        strike: 110,
        quantity: 1,
        premium: 1.0,
        expirationDays: 30,
      },
    ],
    metadata: {
      category: "neutral",
      sentiment: ["neutral"],
      tags: ["Neutral", "Vol Short", "Income"],
      riskLevel: "limited",
      profitPotential: "limited",
      maxProfit: "Net Credit Received",
      maxLoss: "Width of Widest Spread - Net Credit",
      breakeven: "Short Strikes ± Net Credit",
    },
  },
  {
    name: "Iron Butterfly",
    description: "Sell a straddle (ATM call and put) and buy wings (OTM call and put). Maximum profit at the middle strike. A neutral strategy that profits from low volatility.",
    legs: [
      {
        id: "1",
        type: "put",
        position: "long",
        strike: 95,
        quantity: 1,
        premium: 1.5,
        expirationDays: 30,
      },
      {
        id: "2",
        type: "put",
        position: "short",
        strike: 100,
        quantity: 1,
        premium: 4.0,
        expirationDays: 30,
      },
      {
        id: "3",
        type: "call",
        position: "short",
        strike: 100,
        quantity: 1,
        premium: 4.0,
        expirationDays: 30,
      },
      {
        id: "4",
        type: "call",
        position: "long",
        strike: 105,
        quantity: 1,
        premium: 1.5,
        expirationDays: 30,
      },
    ],
    metadata: {
      category: "neutral",
      sentiment: ["neutral"],
      tags: ["Neutral", "Vol Short", "High Reward"],
      riskLevel: "limited",
      profitPotential: "limited",
      maxProfit: "Net Credit Received",
      maxLoss: "Width of Wing - Net Credit",
      breakeven: "Short Strike ± Net Credit",
    },
  },
  {
    name: "Short Straddle",
    description: "Sell a call and put at the same strike. Collect maximum premium. Profit when stock stays near strike. Unlimited risk on both sides.",
    legs: [
      {
        id: "1",
        type: "call",
        position: "short",
        strike: 100,
        quantity: 1,
        premium: 5.0,
        expirationDays: 30,
      },
      {
        id: "2",
        type: "put",
        position: "short",
        strike: 100,
        quantity: 1,
        premium: 4.8,
        expirationDays: 30,
      },
    ],
    metadata: {
      category: "neutral",
      sentiment: ["neutral"],
      tags: ["Neutral", "Vol Short", "High Income"],
      riskLevel: "unlimited",
      profitPotential: "limited",
      maxProfit: "Total Premium Received",
      maxLoss: "Unlimited",
      breakeven: "Strike ± Total Premium",
    },
  },
  {
    name: "Short Strangle",
    description: "Sell an OTM call and OTM put. Collect premium from both sides. Wider profit zone than straddle. Unlimited risk if stock moves significantly.",
    legs: [
      {
        id: "1",
        type: "call",
        position: "short",
        strike: 110,
        quantity: 1,
        premium: 2.5,
        expirationDays: 30,
      },
      {
        id: "2",
        type: "put",
        position: "short",
        strike: 90,
        quantity: 1,
        premium: 2.3,
        expirationDays: 30,
      },
    ],
    metadata: {
      category: "neutral",
      sentiment: ["neutral"],
      tags: ["Neutral", "Vol Short", "Income"],
      riskLevel: "unlimited",
      profitPotential: "limited",
      maxProfit: "Total Premium Received",
      maxLoss: "Unlimited",
      breakeven: "Call Strike + Premium / Put Strike - Premium",
    },
  },
  {
    name: "Jade Lizard",
    description: "Sell a put and sell a call spread (short call + long higher call). No upside risk if structured correctly. Profit from neutral to bullish moves.",
    legs: [
      {
        id: "1",
        type: "put",
        position: "short",
        strike: 95,
        quantity: 1,
        premium: 3.0,
        expirationDays: 30,
      },
      {
        id: "2",
        type: "call",
        position: "short",
        strike: 105,
        quantity: 1,
        premium: 2.5,
        expirationDays: 30,
      },
      {
        id: "3",
        type: "call",
        position: "long",
        strike: 110,
        quantity: 1,
        premium: 1.0,
        expirationDays: 30,
      },
    ],
    metadata: {
      category: "neutral",
      sentiment: ["neutral", "bullish"],
      tags: ["Neutral", "Vol Short", "No Upside Risk"],
      riskLevel: "capped",
      profitPotential: "limited",
      maxProfit: "Net Credit Received",
      maxLoss: "Put Strike - Net Credit (downside)",
      breakeven: "Put Strike - Net Credit",
    },
  },

  // ==================== VOLATILITY - LONG ====================
  {
    name: "Long Straddle",
    description: "Buy both a call and put at the same strike. Profit from large price moves in either direction. Maximum loss is total premium paid. Best for high volatility events.",
    legs: [
      {
        id: "1",
        type: "call",
        position: "long",
        strike: 100,
        quantity: 1,
        premium: 5.0,
        expirationDays: 30,
      },
      {
        id: "2",
        type: "put",
        position: "long",
        strike: 100,
        quantity: 1,
        premium: 4.8,
        expirationDays: 30,
      },
    ],
    metadata: {
      category: "volatility_long",
      sentiment: ["directional"],
      tags: ["Volatility", "Vol Long", "Unlimited Profit"],
      riskLevel: "limited",
      profitPotential: "unlimited",
      maxProfit: "Unlimited",
      maxLoss: "Total Premium Paid",
      breakeven: "Strike ± Total Premium",
    },
  },
  {
    name: "Long Strangle",
    description: "Buy an OTM call and OTM put. Lower cost than straddle but requires larger moves. Ideal when expecting significant volatility but unsure of direction.",
    legs: [
      {
        id: "1",
        type: "call",
        position: "long",
        strike: 110,
        quantity: 1,
        premium: 2.5,
        expirationDays: 30,
      },
      {
        id: "2",
        type: "put",
        position: "long",
        strike: 90,
        quantity: 1,
        premium: 2.3,
        expirationDays: 30,
      },
    ],
    metadata: {
      category: "volatility_long",
      sentiment: ["directional"],
      tags: ["Volatility", "Vol Long", "Low Cost"],
      riskLevel: "limited",
      profitPotential: "unlimited",
      maxProfit: "Unlimited",
      maxLoss: "Total Premium Paid",
      breakeven: "Call Strike + Premium / Put Strike - Premium",
    },
  },
  {
    name: "Call Ratio Backspread",
    description: "Sell 1 lower strike call, buy 2 higher strike calls. Bullish volatility strategy. Unlimited upside profit, limited downside risk. Best when expecting big up move.",
    legs: [
      {
        id: "1",
        type: "call",
        position: "short",
        strike: 100,
        quantity: 1,
        premium: 5.0,
        expirationDays: 30,
      },
      {
        id: "2",
        type: "call",
        position: "long",
        strike: 105,
        quantity: 2,
        premium: 2.5,
        expirationDays: 30,
      },
    ],
    metadata: {
      category: "volatility_long",
      sentiment: ["bullish", "very_bullish"],
      tags: ["Bullish", "Vol Long", "Unlimited Profit"],
      riskLevel: "limited",
      profitPotential: "unlimited",
      maxProfit: "Unlimited",
      maxLoss: "K2 - K1 - Net Credit (at K2)",
      breakeven: "K2 + Max Loss / K1 - Net Credit",
    },
  },
  {
    name: "Put Ratio Backspread",
    description: "Sell 1 higher strike put, buy 2 lower strike puts. Bearish volatility strategy. Large profit if stock crashes, limited risk if stock rises.",
    legs: [
      {
        id: "1",
        type: "put",
        position: "short",
        strike: 100,
        quantity: 1,
        premium: 5.0,
        expirationDays: 30,
      },
      {
        id: "2",
        type: "put",
        position: "long",
        strike: 95,
        quantity: 2,
        premium: 2.5,
        expirationDays: 30,
      },
    ],
    metadata: {
      category: "volatility_long",
      sentiment: ["bearish", "very_bearish"],
      tags: ["Bearish", "Vol Long", "High Profit"],
      riskLevel: "limited",
      profitPotential: "capped",
      maxProfit: "K2 - Net Debit (if stock to $0)",
      maxLoss: "K1 - K2 - Net Credit (at K2)",
      breakeven: "K2 - Max Loss / K1 + Net Credit",
    },
  },
  {
    name: "Inverse Iron Condor",
    description: "Buy an OTM put spread and call spread. Profit when stock moves significantly in either direction. Limited risk and limited reward. Long volatility play.",
    legs: [
      {
        id: "1",
        type: "put",
        position: "short",
        strike: 90,
        quantity: 1,
        premium: 1.0,
        expirationDays: 30,
      },
      {
        id: "2",
        type: "put",
        position: "long",
        strike: 95,
        quantity: 1,
        premium: 2.0,
        expirationDays: 30,
      },
      {
        id: "3",
        type: "call",
        position: "long",
        strike: 105,
        quantity: 1,
        premium: 2.0,
        expirationDays: 30,
      },
      {
        id: "4",
        type: "call",
        position: "short",
        strike: 110,
        quantity: 1,
        premium: 1.0,
        expirationDays: 30,
      },
    ],
    metadata: {
      category: "volatility_long",
      sentiment: ["directional"],
      tags: ["Volatility", "Vol Long", "Limited Risk"],
      riskLevel: "limited",
      profitPotential: "limited",
      maxProfit: "Width of Spread - Net Debit",
      maxLoss: "Net Debit Paid",
      breakeven: "Inner Strikes ± Net Debit",
    },
  },

  // ==================== VOLATILITY - SHORT ====================

  // ==================== BUTTERFLIES ====================
  {
    name: "Long Call Butterfly",
    description: "Buy 1 ITM call, sell 2 ATM calls, buy 1 OTM call. Profit when stock closes at middle strike. Low cost with limited risk. A neutral, short volatility strategy.",
    legs: [
      {
        id: "1",
        type: "call",
        position: "long",
        strike: 95,
        quantity: 1,
        premium: 7.0,
        expirationDays: 30,
      },
      {
        id: "2",
        type: "call",
        position: "short",
        strike: 100,
        quantity: 2,
        premium: 5.0,
        expirationDays: 30,
      },
      {
        id: "3",
        type: "call",
        position: "long",
        strike: 105,
        quantity: 1,
        premium: 3.5,
        expirationDays: 30,
      },
    ],
    metadata: {
      category: "butterflies",
      sentiment: ["neutral"],
      tags: ["Neutral", "Vol Short", "Low Cost"],
      riskLevel: "limited",
      profitPotential: "limited",
      maxProfit: "Width of Wing - Net Debit",
      maxLoss: "Net Debit Paid",
      breakeven: "K1 + Debit / K3 - Debit",
    },
  },
  {
    name: "Long Put Butterfly",
    description: "Buy 1 OTM put, sell 2 ATM puts, buy 1 ITM put. Same profit profile as call butterfly. Maximum profit at middle strike.",
    legs: [
      {
        id: "1",
        type: "put",
        position: "long",
        strike: 95,
        quantity: 1,
        premium: 2.0,
        expirationDays: 30,
      },
      {
        id: "2",
        type: "put",
        position: "short",
        strike: 100,
        quantity: 2,
        premium: 4.0,
        expirationDays: 30,
      },
      {
        id: "3",
        type: "put",
        position: "long",
        strike: 105,
        quantity: 1,
        premium: 7.0,
        expirationDays: 30,
      },
    ],
    metadata: {
      category: "butterflies",
      sentiment: ["neutral"],
      tags: ["Neutral", "Vol Short", "Low Cost"],
      riskLevel: "limited",
      profitPotential: "limited",
      maxProfit: "Width of Wing - Net Debit",
      maxLoss: "Net Debit Paid",
      breakeven: "K1 + Debit / K3 - Debit",
    },
  },
  {
    name: "Broken Wing Butterfly",
    description: "An asymmetric butterfly with unequal wing widths. Can be structured for a credit or small debit. Directional bias with defined risk.",
    legs: [
      {
        id: "1",
        type: "call",
        position: "long",
        strike: 100,
        quantity: 1,
        premium: 5.0,
        expirationDays: 30,
      },
      {
        id: "2",
        type: "call",
        position: "short",
        strike: 105,
        quantity: 2,
        premium: 3.0,
        expirationDays: 30,
      },
      {
        id: "3",
        type: "call",
        position: "long",
        strike: 115,
        quantity: 1,
        premium: 1.0,
        expirationDays: 30,
      },
    ],
    metadata: {
      category: "butterflies",
      sentiment: ["neutral", "bullish"],
      tags: ["Neutral", "Vol Short", "Asymmetric"],
      riskLevel: "limited",
      profitPotential: "limited",
      maxProfit: "K2 - K1 - Net Debit",
      maxLoss: "Net Debit (down) / Wing Width - Max Profit (up)",
      breakeven: "K1 + Net Debit",
    },
  },

  // ==================== ADVANCED / EXOTIC ====================
  {
    name: "Strip",
    description: "Buy 1 ATM call and 2 ATM puts. Bearish volatility bias. Profits more from downside moves than upside. Best when expecting big down move.",
    legs: [
      {
        id: "1",
        type: "call",
        position: "long",
        strike: 100,
        quantity: 1,
        premium: 5.0,
        expirationDays: 30,
      },
      {
        id: "2",
        type: "put",
        position: "long",
        strike: 100,
        quantity: 2,
        premium: 4.5,
        expirationDays: 30,
      },
    ],
    metadata: {
      category: "advanced",
      sentiment: ["bearish", "directional"],
      tags: ["Bearish Bias", "Vol Long", "High Cost"],
      riskLevel: "limited",
      profitPotential: "capped",
      maxProfit: "2 × Strike - Premium (if stock to $0)",
      maxLoss: "Total Premium Paid",
      breakeven: "Strike ± Premium/3 (approx)",
    },
  },
  {
    name: "Strap",
    description: "Buy 2 ATM calls and 1 ATM put. Bullish volatility bias. Profits more from upside moves than downside. Best when expecting big up move.",
    legs: [
      {
        id: "1",
        type: "call",
        position: "long",
        strike: 100,
        quantity: 2,
        premium: 5.0,
        expirationDays: 30,
      },
      {
        id: "2",
        type: "put",
        position: "long",
        strike: 100,
        quantity: 1,
        premium: 4.5,
        expirationDays: 30,
      },
    ],
    metadata: {
      category: "advanced",
      sentiment: ["bullish", "directional"],
      tags: ["Bullish Bias", "Vol Long", "High Cost"],
      riskLevel: "limited",
      profitPotential: "unlimited",
      maxProfit: "Unlimited",
      maxLoss: "Total Premium Paid",
      breakeven: "Strike ± Premium/3 (approx)",
    },
  },
  {
    name: "Guts",
    description: "Buy an ITM call and ITM put. Similar to strangle but with higher cost and intrinsic value. Profits from large moves in either direction.",
    legs: [
      {
        id: "1",
        type: "call",
        position: "long",
        strike: 95,
        quantity: 1,
        premium: 7.0,
        expirationDays: 30,
      },
      {
        id: "2",
        type: "put",
        position: "long",
        strike: 105,
        quantity: 1,
        premium: 7.0,
        expirationDays: 30,
      },
    ],
    metadata: {
      category: "advanced",
      sentiment: ["directional"],
      tags: ["Volatility", "Vol Long", "High Cost"],
      riskLevel: "limited",
      profitPotential: "unlimited",
      maxProfit: "Unlimited",
      maxLoss: "Premium - Intrinsic Width",
      breakeven: "K1 - Net Cost / K2 + Net Cost",
    },
  },
  {
    name: "Short Guts",
    description: "Sell an ITM call and ITM put. High premium collection. Profits when stock stays between strikes. High margin requirement and unlimited risk.",
    legs: [
      {
        id: "1",
        type: "call",
        position: "short",
        strike: 95,
        quantity: 1,
        premium: 7.0,
        expirationDays: 30,
      },
      {
        id: "2",
        type: "put",
        position: "short",
        strike: 105,
        quantity: 1,
        premium: 7.0,
        expirationDays: 30,
      },
    ],
    metadata: {
      category: "advanced",
      sentiment: ["neutral"],
      tags: ["Neutral", "Vol Short", "High Income"],
      riskLevel: "unlimited",
      profitPotential: "limited",
      maxProfit: "Premium - Intrinsic Width",
      maxLoss: "Unlimited",
      breakeven: "K1 - Net Credit / K2 + Net Credit",
    },
  },
  {
    name: "Calendar Spread",
    description: "Sell a near-term option and buy a longer-term option at the same strike. Profits from time decay differential. Best when stock stays near strike.",
    legs: [
      {
        id: "1",
        type: "call",
        position: "short",
        strike: 100,
        quantity: 1,
        premium: 2.5,
        expirationDays: 15,
      },
      {
        id: "2",
        type: "call",
        position: "long",
        strike: 100,
        quantity: 1,
        premium: 4.0,
        expirationDays: 45,
      },
    ],
    metadata: {
      category: "advanced",
      sentiment: ["neutral"],
      tags: ["Neutral", "Theta+", "Time Dependent"],
      riskLevel: "limited",
      profitPotential: "limited",
      maxProfit: "Varies (time-dependent)",
      maxLoss: "Net Debit Paid",
      breakeven: "Complex (IV + time dependent)",
    },
  },
  {
    name: "Diagonal Spread",
    description: "Sell a near-term option and buy a longer-term option at different strikes. Combines calendar and vertical spread characteristics.",
    legs: [
      {
        id: "1",
        type: "call",
        position: "short",
        strike: 105,
        quantity: 1,
        premium: 2.0,
        expirationDays: 15,
      },
      {
        id: "2",
        type: "call",
        position: "long",
        strike: 100,
        quantity: 1,
        premium: 5.0,
        expirationDays: 45,
      },
    ],
    metadata: {
      category: "advanced",
      sentiment: ["bullish", "neutral"],
      tags: ["Bullish", "Theta+", "Time Dependent"],
      riskLevel: "limited",
      profitPotential: "limited",
      maxProfit: "Varies (time-dependent)",
      maxLoss: "Net Debit Paid",
      breakeven: "Complex (IV + time dependent)",
    },
  },
  {
    name: "Double Diagonal",
    description: "Combines two diagonal spreads - one with puts and one with calls. Profits from time decay while allowing movement in either direction.",
    legs: [
      {
        id: "1",
        type: "put",
        position: "short",
        strike: 95,
        quantity: 1,
        premium: 1.5,
        expirationDays: 15,
      },
      {
        id: "2",
        type: "put",
        position: "long",
        strike: 90,
        quantity: 1,
        premium: 2.5,
        expirationDays: 45,
      },
      {
        id: "3",
        type: "call",
        position: "short",
        strike: 105,
        quantity: 1,
        premium: 1.5,
        expirationDays: 15,
      },
      {
        id: "4",
        type: "call",
        position: "long",
        strike: 110,
        quantity: 1,
        premium: 2.5,
        expirationDays: 45,
      },
    ],
    metadata: {
      category: "advanced",
      sentiment: ["neutral"],
      tags: ["Neutral", "Theta+", "Complex"],
      riskLevel: "limited",
      profitPotential: "limited",
      maxProfit: "Varies (time-dependent)",
      maxLoss: "Net Debit Paid",
      breakeven: "Complex (IV + time dependent)",
    },
  },
];

// Helper function to get strategies by category
export function getStrategiesByCategory(category: StrategyCategory): ExtendedStrategy[] {
  return strategyTemplates.filter((s) => s.metadata.category === category);
}

// Helper function to get strategies by sentiment
export function getStrategiesBySentiment(sentiment: StrategySentiment): ExtendedStrategy[] {
  return strategyTemplates.filter((s) => s.metadata.sentiment.includes(sentiment));
}
