import type { Strategy } from "@shared/schema";

export const strategyTemplates: Omit<Strategy, "id" | "underlyingPrice">[] = [
  {
    name: "Long Call",
    description: "Buy a call option to profit from upside movement. Limited risk, unlimited profit potential.",
    legs: [
      {
        id: "1",
        type: "call",
        position: "long",
        strike: 105,
        quantity: 1,
        premium: 3.5,
        expirationDays: 30,
      },
    ],
  },
  {
    name: "Long Put",
    description: "Buy a put option to profit from downside movement. Limited risk, high profit potential.",
    legs: [
      {
        id: "1",
        type: "put",
        position: "long",
        strike: 95,
        quantity: 1,
        premium: 3.0,
        expirationDays: 30,
      },
    ],
  },
  {
    name: "Covered Call",
    description: "Hold stock and sell a call. Generate income while capping upside potential.",
    legs: [
      {
        id: "1",
        type: "call",
        position: "short",
        strike: 110,
        quantity: 1,
        premium: 2.5,
        expirationDays: 30,
      },
    ],
  },
  {
    name: "Protective Put",
    description: "Hold stock and buy a put. Insurance against downside while keeping upside.",
    legs: [
      {
        id: "1",
        type: "put",
        position: "long",
        strike: 95,
        quantity: 1,
        premium: 3.0,
        expirationDays: 30,
      },
    ],
  },
  {
    name: "Bull Call Spread",
    description: "Buy lower strike call, sell higher strike call. Limited risk and profit.",
    legs: [
      {
        id: "1",
        type: "call",
        position: "long",
        strike: 100,
        quantity: 1,
        premium: 5.0,
        expirationDays: 30,
      },
      {
        id: "2",
        type: "call",
        position: "short",
        strike: 110,
        quantity: 1,
        premium: 2.0,
        expirationDays: 30,
      },
    ],
  },
  {
    name: "Bear Put Spread",
    description: "Buy higher strike put, sell lower strike put. Profit from moderate downside.",
    legs: [
      {
        id: "1",
        type: "put",
        position: "long",
        strike: 100,
        quantity: 1,
        premium: 5.0,
        expirationDays: 30,
      },
      {
        id: "2",
        type: "put",
        position: "short",
        strike: 90,
        quantity: 1,
        premium: 2.0,
        expirationDays: 30,
      },
    ],
  },
  {
    name: "Long Straddle",
    description: "Buy call and put at same strike. Profit from large moves in either direction.",
    legs: [
      {
        id: "1",
        type: "call",
        position: "long",
        strike: 100,
        quantity: 1,
        premium: 5.0,
        expirationDays: 30,
      },
      {
        id: "2",
        type: "put",
        position: "long",
        strike: 100,
        quantity: 1,
        premium: 4.8,
        expirationDays: 30,
      },
    ],
  },
  {
    name: "Long Strangle",
    description: "Buy out-of-the-money call and put. Lower cost than straddle for volatility plays.",
    legs: [
      {
        id: "1",
        type: "call",
        position: "long",
        strike: 110,
        quantity: 1,
        premium: 2.5,
        expirationDays: 30,
      },
      {
        id: "2",
        type: "put",
        position: "long",
        strike: 90,
        quantity: 1,
        premium: 2.3,
        expirationDays: 30,
      },
    ],
  },
  {
    name: "Iron Condor",
    description: "Sell call and put spreads. Profit when price stays in a range.",
    legs: [
      {
        id: "1",
        type: "put",
        position: "short",
        strike: 95,
        quantity: 1,
        premium: 2.0,
        expirationDays: 30,
      },
      {
        id: "2",
        type: "put",
        position: "long",
        strike: 90,
        quantity: 1,
        premium: 1.0,
        expirationDays: 30,
      },
      {
        id: "3",
        type: "call",
        position: "short",
        strike: 105,
        quantity: 1,
        premium: 2.0,
        expirationDays: 30,
      },
      {
        id: "4",
        type: "call",
        position: "long",
        strike: 110,
        quantity: 1,
        premium: 1.0,
        expirationDays: 30,
      },
    ],
  },
  {
    name: "Butterfly Spread",
    description: "Buy 1 low, sell 2 middle, buy 1 high. Profit from low volatility at middle strike.",
    legs: [
      {
        id: "1",
        type: "call",
        position: "long",
        strike: 95,
        quantity: 1,
        premium: 7.0,
        expirationDays: 30,
      },
      {
        id: "2",
        type: "call",
        position: "short",
        strike: 100,
        quantity: 2,
        premium: 5.0,
        expirationDays: 30,
      },
      {
        id: "3",
        type: "call",
        position: "long",
        strike: 105,
        quantity: 1,
        premium: 3.5,
        expirationDays: 30,
      },
    ],
  },
];
