// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/hero-cc-refined-b/RefineB1.tsx": () => import("../components/mockups/hero-cc-refined-b/RefineB1.tsx"),
  "./components/mockups/hero-cc-refined-b/RefineB2.tsx": () => import("../components/mockups/hero-cc-refined-b/RefineB2.tsx"),
  "./components/mockups/hero-polish/Polish1.tsx": () => import("../components/mockups/hero-polish/Polish1.tsx"),
  "./components/mockups/hero-polish/Polish2.tsx": () => import("../components/mockups/hero-polish/Polish2.tsx"),
  "./components/mockups/hero-variations/CommandCenter.tsx": () => import("../components/mockups/hero-variations/CommandCenter.tsx"),
  "./components/mockups/hero-variations/CommandCenterR1.tsx": () => import("../components/mockups/hero-variations/CommandCenterR1.tsx"),
  "./components/mockups/hero-variations/CommandCenterR2.tsx": () => import("../components/mockups/hero-variations/CommandCenterR2.tsx"),
  "./components/mockups/hero-variations/ProductFirst.tsx": () => import("../components/mockups/hero-variations/ProductFirst.tsx"),
  "./components/mockups/hero-variations/SocialProofLed.tsx": () => import("../components/mockups/hero-variations/SocialProofLed.tsx"),
  "./components/mockups/hero-variations-copy-rwy4vDuo/CommandCenter.tsx": () => import("../components/mockups/hero-variations-copy-rwy4vDuo/CommandCenter.tsx"),
  "./components/mockups/hero-variations-copy-rwy4vDuo/CommandCenterR2.tsx": () => import("../components/mockups/hero-variations-copy-rwy4vDuo/CommandCenterR2.tsx"),
  "./components/mockups/hero-variations-copy-rwy4vDuo/HeroVariationsCopyRwy4vDuo.tsx": () => import("../components/mockups/hero-variations-copy-rwy4vDuo/HeroVariationsCopyRwy4vDuo.tsx"),
  "./components/mockups/hero-variations-copy-rwy4vDuo/ProductFirst.tsx": () => import("../components/mockups/hero-variations-copy-rwy4vDuo/ProductFirst.tsx"),
  "./components/mockups/hero-variations-copy-rwy4vDuo/SocialProofLed.tsx": () => import("../components/mockups/hero-variations-copy-rwy4vDuo/SocialProofLed.tsx"),
  "./components/mockups/hero-variations-copy-v1Sj6fvN/HeroVariationsCopyV1Sj6fvN.tsx": () => import("../components/mockups/hero-variations-copy-v1Sj6fvN/HeroVariationsCopyV1Sj6fvN.tsx"),
  "./components/mockups/hero-variations-copy-v1Sj6fvN/ProductFirst.tsx": () => import("../components/mockups/hero-variations-copy-v1Sj6fvN/ProductFirst.tsx"),
  "./components/mockups/hero-variations-copy-v1Sj6fvN/SocialProofLed.tsx": () => import("../components/mockups/hero-variations-copy-v1Sj6fvN/SocialProofLed.tsx")
};
