// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/hero-variations/CommandCenter.tsx": () => import("../components/mockups/hero-variations/CommandCenter.tsx"),
  "./components/mockups/hero-variations/ProductFirst.tsx": () => import("../components/mockups/hero-variations/ProductFirst.tsx"),
  "./components/mockups/hero-variations/SocialProofLed.tsx": () => import("../components/mockups/hero-variations/SocialProofLed.tsx")
};
